---
title: "WUp-Linear-Model-with-prediction-2"
author: "Maximiliano Ortiz"
date: "2025-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tigerstats)
require(knitr)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)  
```

###Model1: Sims-ARM

```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=ARM))
```

```{r}
basicNN + geom_point() + ggtitle("SIMS vs ARM") +theme (plot.title = element_text(hjust = 0.5, size = 20))

```


###Numerical Results

```{r}
cor(SIMS~ARM,data=data)
```

###Inferintal Results

```{r}
model.1 <- lm(SIMS~ARM,data=data)
summary.lm(model.1)
```

### Create target

```{r}
target <- data.frame(ARM=90,GRIP=90)
```

### Predict Target Point of Model 1

```{r}
predict(model.1,target,interval =c("prediction"))
```


### Linear Fit Model1

```{r}
basicNN + geom_point () + ggtitle("SIMS-ARM") + theme(plot.title = element_text(hjust = 0.5, size = 20)) + geom_smooth(method = lm)
```


##Model2: Sims~GRIP
```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=GRIP))
```

```{r}
basicNN + geom_point() +ggtitle("SIMS vs GRIP")+ theme(plot.title = element_text(hjust=0.5,size=20))
```


###Numerical Results

```{r}
cor(SIMS~GRIP,data=data)
```

###Inferintal Results

```{r}
model.2 <- lm(SIMS~GRIP,data=data)
summary.lm(model.2)
```


### Predict Target Point of Model 2

```{r}
predict(model.2,target,interval =c("prediction"))
```


### Linear Fit Model2

```{r}
basicNN + geom_point () + ggtitle("SIMS-GRIP") + theme(plot.title = element_text(hjust = 0.5, size = 20)) + geom_smooth(method = lm)
```




